#!/bin/bash

function displayhelp {
    echo "$0 [ --debug | --release ]"
}

DEBUG_SET=false
RELEASE_SET=false

while [ -n "$1" ]
do
    case "$1" in
        -d | --debug)
            DEBUG_SET=true
            RELEASE_SET=false
            ;;

        -h | --help)
            displayhelp
            exit
            ;;

        -r | --release)
            RELEASE_SET=true
            DEBUG_SET=false
            ;;

    esac

    # We're done with the current argument, move to the next.
    shift
done

BUILD_TYPE=

if [ $DEBUG_SET == true ]; then
    BUILD_TYPE=Debug
else
    BUILD_TYPE=Release
fi

# Generate the makefile with cmake
cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE
